name: 📸 Controllo Foto SKU

on:
  workflow_dispatch:       # Avvio manuale
  schedule:
    - cron: '0 5 * * *'     # Ogni giorno alle 5:00 UTC

jobs:
  check-photos:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Installa dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_actions.txt

      - name: 🔐 Imposta variabili segrete
        env:
          FOTO_GSHEET_ID: ${{ secrets.FOTO_GSHEET_ID }}
          SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
        run: |
          echo "✅ Variabili segrete impostate"

      - name: 🚀 Avvia script controllo foto
        env:
          FOTO_GSHEET_ID: ${{ secrets.FOTO_GSHEET_ID }}
          SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
        run: python scripts/check_photos.py
